<?php
$labels = array();
$labels['vacation'] = 'Abwesenheit';
$labels['headline'] = 'Automatische Antwort bei Abwesenheit konfigurieren';
$labels['autoreplyenabled'] = "Aktiviert";
$labels['autoreplysubject'] = 'Betreff';
$labels['autoreplymessage'] = 'Nachricht';
$labels['autoreplybutton'] = 'Speichern';
$labels['success_changed'] = 'Einstellungen erfolgreich gespeichert';
$labels['failed'] = 'Fehler beim Speichern';
?>
