<?php
$labels = array();
$labels['vacation'] = 'Vacation';
$labels['headline'] = 'Configure automatic response';
$labels['autoreplyenabled'] = "Enabled";
$labels['autoreplysubject'] = 'Subject';
$labels['autoreplymessage'] = 'Message';
$labels['autoreplybutton'] = 'Save';
$labels['success_changed'] = 'Vacation settings succesfully changed';
$labels['failed'] = 'Changing vacation settings failed!';
?>
